Use __FILE__ instead of  __file__
Fixes the error:

```
   ActionView::Template::Error:
        undefined local variable or method `__file__' for #<ActionView::Base:0x000000004cd650>
        Did you mean?  __FILE__
                       __LINE__
```