Rename 'Blacklight' inside of core.js as 'Core'
When bundled into one file such as the 'blacklight.esm.js' this file produces, it was resulting in a conflict with top-level Blacklight module, and resulting in error 'Uncaught TypeError: Blacklight.activate is not a function'